'use client'
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";
import { ThemeProvider } from "@/components/theme-provider";
import { Toaster } from "@/components/ui/toaster";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import Head from "next/head";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const metadata = {
  title: "Uleash Ideas",
  description: "Generated by create analitiecs",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const queryClient = new QueryClient();
  // const queryClient = new QueryClient()
  return (
    <html lang="en" suppressHydrationWarning>
      <Head>
        <title>{metadata?.title}</title>
        <meta name="description" content={metadata?.description} />
        {/* Other meta tags can go here */}
      </Head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <QueryClientProvider client={queryClient}>
            <SidebarProvider >
              <AppSidebar />
              <SidebarInset>
                <main>
                  <div className="">
                    {children}
                    <Toaster />
                  </div>
                </main>
              </SidebarInset>

            </SidebarProvider>
          </QueryClientProvider>
        </ThemeProvider>

      </body>
    </html>
  );
}
